### ISSUE TITLE
Mesa 22.3.4 apt conflict with Amber 21.3.7

### ISSUE THREAD

**Issue by bmunger** [pop-os/mesa#14]
When running an apt upgrade, there is a conflict with the i915 driver in the Mesa 22.3.4 package.  According to the Mesa project site (https://docs.mesa3d.org/amber.html) the i915 was moved from the main sources to Amber.  However it looks like Pop_OS has i915 still in libgl1-mesa-dri which conflicts with libgl1-amber-dri.  Below is the output from apt upgrade:

```
Preparing to unpack .../libgl1-mesa-dri_22.3.4-1pop1~1675300365~22.04~6b66c01_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (22.3.4-1pop1~1675300365~22.04~6b66c01) over (22.2.0-1pop0~1664294850~22.04~4e1b64f) ...
dpkg: error processing archive /var/cache/apt/archives/libgl1-mesa-dri_22.3.4-1pop1~1675300365~22.04~6b66c01_amd64.deb (--unpa
ck):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/dri/i915_dri.so', which is also in package libgl1-amber-dri:amd64 21.3.7-0ubun
tu1
Errors were encountered while processing:
 /var/cache/apt/archives/libgl1-mesa-dri_22.3.4-1pop1~1675300365~22.04~6b66c01_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by 13r0ck** [comment]
Maybe fixed by https://github.com/pop-os/mesa/pull/15

Can you try adding it to your system and see if the upgrade is successful?
`sudo apt-manage add popdev:amber && sudo apt update && sudo apt upgrade -y`?

**Comment by SandroCristiano** [comment]
> sudo apt-manage add popdev:amber && sudo apt update && sudo apt upgrade -y

It worked for me, but only after I ran apt --fix-broken install

**Comment by 13r0ck** [comment]
Awesome! Unfortunately `apt --fix-broken install` is to be expected for systems affected by this. Thanks for testing!

**Comment by bmunger** [comment]
Yes, I can also confirm it works as it should.  Thank you!

**Comment by SandroCristiano** [comment]
No problem. Glad I could be of assistance. 

> Awesome! Unfortunately `apt --fix-broken install` is to be expected for systems affected by this. Thanks for testing!

**Comment by tiagoprn** [comment]
I followed the instructions and it worked here also. Only one concern: is it safe  to keep "popdev:amber" on the system after fixing  this problem? If not, how to remove it? Will that "undo" the proposed solution? As I've seen the "staging" on the  repo, I am concerned if another package  breaks in the future  and maybe  renders  the system unusable. Btrfs  snapshots saved  my day today. =D

**Comment by leviport** [comment]
@tiagoprn It is safe to leave it there for now. The source will start to 404 when you do apt updates once the PR is merged and the branch is deleted. At that time, you should remove it with `apt-manage remove popdev-amber`.

**Comment by leviport** [comment]
The fix has been released and will be available very soon. If you added the testing branch, now is a good time to remove it: `apt-manage remove popdev-amber`

**Comment by tiagoprn** [comment]
Thank you @leviport , I've followed your instructions and all is fine now!

**Comment by PyAntony** [comment]
I was getting a similar issue and landed here. I was getting the following when trying to upgrade from *Pop!_Shop*:
```
The following packages have unmet dependencies:
  libgl1-mesa-dri: Breaks: libgl1-mesa-dri (!= 22.3.5-1pop1~1677168864~22.04~8f20e98) but 22.2.0-1pop0~1664294850~22.04~4e1b64f is to be installed
  libgl1-mesa-dri: Depends: libglapi-mesa (= 22.2.0-1pop0~1664294850~22.04~4e1b64f) but 22.3.5-1pop1~1677168864~22.04~8f20e98 is to be installed
                   Breaks: libgl1-mesa-dri (!= 22.2.0-1pop0~1664294850~22.04~4e1b64f) but 22.3.5-1pop1~1677168864~22.04~8f20e98 is to be installed
```

The command that fixed it for me is: `sudo apt-get -u dist-upgrade`. Additioal things to try: https://www.baeldung.com/linux/unmet-dependencies-apt-get
