### ISSUE TITLE
pop os 22.04 VM shows black screen when booting up

### ISSUE THREAD

**Issue by weiklr** [pop-os/mesa#25]
I'm running Pop OS 22.04 on a VM using qemu and virt-manager. Everything was working fine until I ran apt update to update my packages. When i boot up i only see a black screen, although i was still able to ssh into the VM.

I troubleshoot by doing a separate fresh VM installation of Pop OS 22.04,  and found the issue seems related to mesa. The version of my mesa and related packages are `23.3.0-1pop0~1702935939~22.04~67e417a`. 

When i update mesa, this fresh installation gives a black screen, if i apt-mark hold mesa and related packages, then it works fine.

Will this be fixed when Pop OS updates to a newer version of mesa packages?

**Comment by chrisfonte** [comment]
Isn't this the same issue as https://github.com/pop-os/mesa/issues/26 ?

**Comment by leviport** [comment]
Looks like it. I'll close this one as a duplicate since there is more info and interaction in https://github.com/pop-os/mesa/issues/26
